# Generated by Django 2.2.1 on 2019-05-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_mydcim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mydcim',
            field=models.ImageField(blank=True, upload_to='mydcim/%Y%m%d/'),
        ),
    ]
